### ISSUE TITLE
Bug: Hardcoded separator "_" doesn't work for 10X H5 format, in scATAC_genescore.py

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#1]
The following line for calculating RP scores assumes that peaks are named as "chr_start_end" in peak matrix.

https://github.com/liulab-dfci/MAESTRO/blob/ffdfffe0a28bf8e42cf86a63697d0ab40b78ade7/MAESTRO/scATAC_genescore.py#L97

However, the standard output "filtered_peak_bc_matrix.h5" from 10X cellranger-atac may use chr:start-end", according to

https://support.10xgenomics.com/single-cell-atac/software/pipelines/latest/advanced/h5_matrices

Suggest replacing the separator in the peak column to a standard character (either "_" or "-") in MAESTRO R script after loading the H5 file.

**Comment by chenfeiwang** [comment]
Hi Tao, the peaks generated by MAESTRO will be separated using "_" and can run smoothly with the scATAC_genescore code. 

In the latest version of MAESTRO, we implemented the gene score function in R, and replace the separator of all the input peaks to standard "_", which will be consistent with the python code thus solve the problem. Thanks for reporting this bug!

Let me know if you still facing problems.
