### ISSUE TITLE
Enhancement: Description in the HTML report

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#10]
The current (v1.0.2) HTML report only includes figures and tables without explanations. Please add more texts explaining how to interpret the results in the report.

https://github.com/liulab-dfci/MAESTRO/tree/master/MAESTRO/html

**Comment by DongqingSun96** [comment]
Hi Tao,

Thanks for this suggestion. In the latest  HTML report, we have added some brief texts, something like figure legends, to explain the figures and tables. If there's any improvement we can make, please let me know. 

Thanks!
Dongqing
