### ISSUE TITLE
1.3.1 release not available in conda channel

### ISSUE THREAD

**Issue by mengxiao** [liulab-dfci/MAESTRO#100]
Hi there,

I think the 1.3.1 release hasn't been uploaded to the `liulab-dfci` channel yet, so the current installation instructions throw an error.

**Comment by crazyhottommy** [comment]
Thanks for reporting this. We are aware of that. we used up the Travis build credit and the build is not triggered and that's why it is not uploaded to the conda channel. you should be able to install 1.3.0. We are working on it to fix that.

**Comment by mengxiao** [comment]
Ah - ok. I hope they grant you some more credits soon. Thanks!

**Comment by crazyhottommy** [comment]
you can install v1.3.1 for the moment at https://anaconda.org/baigal628/maestro
we will upload to dfci-liulab after we fix it.

**Comment by crazyhottommy** [comment]
This is fixed now. Thanks!
