### ISSUE TITLE
About "EOF in multi-line statement"

### ISSUE THREAD

**Issue by bluesky2003** [liulab-dfci/MAESTRO#101]
When trying the docker case, after scatac-init,  snakemake  execution gave the following:

SyntaxError in line 1160 of /software/Res/Snakefile:
EOF in multi-line statement (Snakefile, line 1160)

How to address it ?

**Comment by crazyhottommy** [comment]
@baigal628 can we release a new docker version for v1.3.1?

**Comment by crazyhottommy** [comment]
We will release a new bug fix and a new docker image for that. Thanks for your patience.

**Comment by mengxiao** [comment]
@bluesky2003 I've submitted PR #106 to fix this (hopefully done correctly- the maintainers can verify). Until it's merged, you can manually implement the patch inside your docker image.

**Comment by cadyyuheng** [comment]
I just installed MAESTRO on linux and received the same error.

**Comment by crazyhottommy** [comment]
Hi @cadyyuheng, if you manually change the snakefile according to https://github.com/liulab-dfci/MAESTRO/pull/106/files it should work. We will release a new bug fix this week.

**Comment by cadyyuheng** [comment]
I see. Thanks, @crazyhottommy!

**Comment by liulab-dfci** [comment]
the new v1.3.2 release fixed this.
