### ISSUE TITLE
pbmc.ATAC.res$peaks

### ISSUE THREAD

**Issue by cadyyuheng** [liulab-dfci/MAESTRO#108]
Hello,

I've been doing scATAC-analysis with Seurat. However, I just discovered MAESTRO recently and want to try to identify driver TFs using MAESTRO. To keep my analysis consistent, I want to use my seurat object from the previous analysis directly, which I believe corresponds with pbmc.ATAC.res$atac in the tutorial. However, I wonder what would be the corresponding file for pbmc.ATAC.res$peaks.

Really appreciate your help!

**Comment by crazyhottommy** [comment]
`pbmc.ATAC.res$peaks` is the differential peaks calculated by [`presto`](https://github.com/immunogenomics/presto)

**Comment by cadyyuheng** [comment]
Thanks @crazyhottommy
