### ISSUE TITLE
Error: Failed to install 'MAESTRO' from GitHub

### ISSUE THREAD

**Issue by Pikachu233** [liulab-dfci/MAESTRO#109]
Hi,

I tried to install maestro in r. However, I received following error:
Error: Failed to install 'MAESTRO' from GitHub:
  (converted from warning) installation of package ‘C:/Users/~1/AppData/Local/Temp/RtmpgpQAJ2/file10b03bde77da/MAESTRO_1.3.1.99999.tar.gz’ had non-zero exit status

- Session info --------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows >= 8 x64            
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/Chicago             
 date     2021-01-22                  

- Packages ------------------------------------------------------------------
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.2)
 callr         3.5.1   2020-10-13 [1] CRAN (R 4.0.3)
 cli           2.2.0   2020-11-20 [1] CRAN (R 4.0.3)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.2)
 curl          4.3     2019-12-02 [1] CRAN (R 4.0.2)
 desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.2)
 devtools    * 2.3.2   2020-09-18 [1] CRAN (R 4.0.3)
 digest        0.6.27  2020-10-24 [1] CRAN (R 4.0.3)
 ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.2)
 fansi         0.4.2   2021-01-15 [1] CRAN (R 4.0.3)
 fs            1.5.0   2020-07-31 [1] CRAN (R 4.0.2)
 glue          1.4.2   2020-08-27 [1] CRAN (R 4.0.2)
 lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.2)
 magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.3)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.2)
 pkgbuild      1.2.0   2020-12-15 [1] CRAN (R 4.0.3)
 pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.2)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.2)
 processx      3.4.5   2020-11-30 [1] CRAN (R 4.0.3)
 ps            1.5.0   2020-12-05 [1] CRAN (R 4.0.3)
 purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.2)
 R6            2.5.0   2020-10-28 [1] CRAN (R 4.0.3)
 remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.2)
 rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.3)
 rprojroot     2.0.2   2020-11-15 [1] CRAN (R 4.0.3)
 rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.3)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.2)
 testthat      3.0.1   2020-12-17 [1] CRAN (R 4.0.3)
 usethis     * 2.0.0   2020-12-10 [1] CRAN (R 4.0.3)
 withr         2.4.0   2021-01-16 [1] CRAN (R 4.0.3)
 yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.2)

**Comment by crazyhottommy** [comment]
Hi, it seems that you are using windows. We only tested it in Linux machines. Can you install the whole MAESTRO package via conda?

**Comment by crazyhottommy** [comment]
FYI: I just tried `devtools::install_github("liulab-dfci/MAESTRO")` on my mac, and it worked fine.

**Comment by Pikachu233** [comment]
Thanks! I've never used conda before and just install MAESTRO on it. May I ask how am I supposed to interact it in R if I've already processed my data with cellranger. Also, I'm a little confused, how large is the all.giggle file after decompression? -- it seems to be 18.4Gb w/o decompression.

**Comment by jphe** [comment]
Hi,

I met the same issue when install MAESTRO R package in the linux system.

![image](https://user-images.githubusercontent.com/34993687/106448779-30c96180-64be-11eb-9d27-7cc32e685ee4.png)

I have tried to install it by source, it reported another error.

![image](https://user-images.githubusercontent.com/34993687/106448957-6c642b80-64be-11eb-9b52-0df371af97a4.png)

While I can not find the 'presto' R package, I can only find the 'RPresto' package and installed it, but still the same error.

Thanks,
Jphe

**Comment by crazyhottommy** [comment]
Hi Jphe,
Presto is at https://github.com/immunogenomics/presto
which linux system are you using? it is tested on Ubuntu. I can also install it on my mac without a problem.

**Comment by crazyhottommy** [comment]
> Thanks! I've never used conda before and just install MAESTRO on it. May I ask how am I supposed to interact it in R if I've already processed my data with cellranger. Also, I'm a little confused, how large is the all.giggle file after decompression? -- it seems to be 18.4Gb w/o decompression.

if you already have MAESTRO installed by conda, you can
```bash
$ conda activate MAESTRO
$ R
# within R

> library(MAESTRO)
 
```
Then follow https://github.com/liulab-dfci/MAESTRO/blob/master/example/Integration/Integration.md#step-0-read-the-scrna-seq-and-scatac-seq-clustering-object

```r
> pbmc.coembedded.res <- Incorporate(RNA = your_RNA_seurat, 
                                     ATAC = your_ATAC_seurat, 
                                     project = "10X_PBMC_integrated",
                                     method = "MAESTRO")

```
 the giggle file is big.

**Comment by jphe** [comment]
> Hi Jphe,
> Presto is at https://github.com/immunogenomics/presto
> which linux system are you using? it is tested on Ubuntu. I can also install it on my mac without a problem.

Thanks,
The linux system I use is Red Hat
![image](https://user-images.githubusercontent.com/34993687/106542485-e1774580-653e-11eb-8fe8-01a86b273bf0.png)

I have installed Presto but another error reported. My Seurat version is Seurat_3.9.9.9008. Does the Seurat problem？
![image](https://user-images.githubusercontent.com/34993687/106542932-b9d4ad00-653f-11eb-8798-5b3414f12728.png)

I have tried to install it with conda, but seems it conflict with the other exist environments.
![image](https://user-images.githubusercontent.com/34993687/106543132-1b951700-6540-11eb-81a9-1404e5d27384.png)

I also tried to install it in my Mac, but it always failed to connect to the github, it seems my network problem.
![image](https://user-images.githubusercontent.com/34993687/106543237-44b5a780-6540-11eb-85a6-f14838901191.png)

**Comment by crazyhottommy** [comment]
can you try `devtools::install_github("liulab-dfci/MAESTRO")` again?

**Comment by jphe** [comment]
Still the same error:  Error: Failed to install 'MAESTRO' from GitHub: Line starting 'Encoding ...' is malformed!

![image](https://user-images.githubusercontent.com/34993687/106751148-c9e5ad00-6663-11eb-929e-77e0da3be773.png)

I have another question, how dose MAESTRO deal with the multiple mapped reads, dose it only keep the unique mapped reads with high MAPQ? or by any other ways?

Thanks.

**Comment by jeffsun905** [comment]
Tried to install MAESTRO to R (v4.0.3) and got the exact same error about "CreateGeneActivityMatrixas" as the above. The R is in Ubuntu 20.04. Has anyone solved the issue?
Thanks!

**Error: object ‘CreateGeneActivityMatrix’ is not exported by 'namespace:Seurat'
Execution halted**
ERROR: lazy loading failed for package ‘MAESTRO’
* removing ‘/home/zsun/R/x86_64-pc-linux-gnu-library/4.0/MAESTRO’
Error: Failed to install 'MAESTRO' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmppMBatg/fileaf2d839ace2cf/MAESTRO_2.tar.gz’ had non-zero exit status

**Comment by crazyhottommy** [comment]
Hi, 
It seems to be related with Seurat.  can you install `Seurat` first and then install `MAESTRO`?

**Comment by jeffsun905** [comment]
Thank you for the quick response. Seurat was pre-installed (v3.9.9). I originally thought that could be the reason so I re-installed its latest one (4.0). However, still got the same error.

**Comment by crazyhottommy** [comment]
@jeffsun905  can you directly call `CreateGeneActivityMatrix` after `library(Seurat)`? or you need to `Seurat:::CreateGeneActivityMatrix` to call it?

**Comment by jeffsun905** [comment]
@crazyhottommy Seems like the latest Seurat does not have this function as I can not call that function after loading Seurat using either way.  Maybe there is a compatibility issue between MAESTRO and the newer Seurat? The install error is at very end of testing phase...

**Comment by crazyhottommy** [comment]
Yes, we figured that new version of `Seurat` moved that function to `signac` https://satijalab.org/signac/reference/geneactivity and changed the name.
We will fix this. Thanks for reporting this.

**Comment by crazyhottommy** [comment]
it is related to https://github.com/liulab-dfci/MAESTRO/issues/63
we will fix this in our next release

**Comment by jeffsun905** [comment]
Great and thank you for working on the fix. The new version of Seurat has many good features so would like to keep it.

**Comment by crazyhottommy** [comment]
We just released MAESTRO 1.4.0 which is SeuratV4 compatible. Can you please try it and let us know? Thanks!

**Comment by jeffsun905** [comment]
Thank you for the new release Ming! Yes, it has been successfully installed (first try failed but after installing "EnsDb.Mmusculus.v79", it succeeded as it appears it is required by Maestro.

**Comment by crazyhottommy** [comment]
No problem! closing it now.

**Comment by alekseybelikov** [comment]
https://github.com/liulab-dfci/MAESTRO/issues/172#issue-2739017187
