### ISSUE TITLE
Enhancement: Provide options to set customized cell signatures in Snakemake configuration file

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#11]
In the current version 1.0.2, if users use the snakemake pipeline, there is no way to set their customized cell signatures, and they are forced to use CIBERSORT immune cell signatures. The pipeline would be more useful if the cell annotation results from snakemake pipeline can make more sense.

https://github.com/liulab-dfci/MAESTRO/tree/master/MAESTRO/Snakemake

**Comment by DongqingSun96** [comment]
Hi Tao,

Thanks for this suggestion. In the latest version of MAESTRO, we provide the option to set the  custom cell signature through the two arguments both in scRNA and scATAC. https://github.com/liulab-dfci/MAESTRO/blob/1fd24fba59ad5074d37ac30e5b81c24a8bbf0d7c/MAESTRO/Snakemake/scRNA/config.yaml#L16-L20

Thanks!
Dongqing

**Comment by taoliu** [comment]
Thanks! I will give it a try!
