### ISSUE TITLE
A bug in Snakemake/scRNA/Snakefile

### ISSUE THREAD

**Issue by QiangTU** [liulab-dfci/MAESTRO#110]
Hi, I am using v1.3.1, and found a bug in Snakemake/scRNA/Snakefile:

```
shell:
        "python " + SCRIPT_PATH + "/lisa_path.py --species {params.species} --input {params.lisadir} "
        "Rscript " + RSCRIPT_PATH + "/scRNAseq_pipe.R --expression {params.expression} --species {params.species} "
        "--prefix {params.outpre} --signature {params.signature} "
        "--outdir {params.outdir} --thread {threads}"
```

There should be a `;` at the end of the lisa_path line.

When I manually fixed this problem, the pipeline complained: 

```
lisa: error: invalid choice: 'unpack' (choose from 'oneshot', 'multi', 'regions', 'coverage', 'download', 'install', 'run-tests')
```

So there might be some more problems with lisa_path.py? It only does `unpack`.

**Comment by crazyhottommy** [comment]
this is because we had lisa2 updated so it breaks. we will specify the version of lisa2 in the next release to fix this. Thanks for the report.

**Comment by QiangTU** [comment]
Thanks a lot! I installed v1.3.1 by mama, how can I upgrade it to v1.3.2?

**Comment by crazyhottommy** [comment]
It is better to create a new env for the new version. I will reply here when it is out.
or you can try `mamba update`. I did not test.

**Comment by crazyhottommy** [comment]
@QiangTU  the new version fixed this. `mamba create -n MAESTRO maestro=1.3.2 -c liulab-dfci`
