### ISSUE TITLE
picard: command not found

### ISSUE THREAD

**Issue by jphe** [liulab-dfci/MAESTRO#113]
Hi, 

I'm running MAESTRO scATAC-seq with bam file according to the manual, and it reports an error: /bin/bash: picard: command not found.

![image](https://user-images.githubusercontent.com/34993687/106574050-5feeda00-6575-11eb-9cde-d1733afb49a7.png)

Does the picard represents the javar picard (https://gatk.broadinstitute.org/hc/en-us/articles/360037052812-MarkDuplicates-Picard-)? if so, seems it need to be run with "java -jar"? 
And I find another python picard  (https://pypi.org/project/picard/) in pip, but it seems a music tagger and none business with bam files.

Bellow is my script:

 MAESTRO scatac-init --platform 10x-genomics --format bam --species GRCh38 \
        --bam ../atac_pbmc_10k_v1_possorted_bam.bam \
        --cores 10 --directory PBMC_10k_MAESTRO_bam --outprefix 10X_PBMC_10k \
        --peak-cutoff 100 --count-cutoff 1000 --frip-cutoff 0.2 --cell-cutoff 50 \
        --rpmodel Enhanced \
        --giggleannotation ../giggle.all \
        --annotation --method both --signature human.immune.CIBERSORT --clusterpeak

Thanks,
Jphe

**Comment by crazyhottommy** [comment]
Hi,
Did you install MAESTRO by conda? If so, picard should be on your $PATH

```bash
conda activate MAESTRO1.3.2
(MAESTRO1.3.2) [mtang@kraken1 singularity_images]$ which picard
~/anaconda3/envs/MAESTRO1.3.2/bin/picard
```

**Comment by jphe** [comment]
Thanks, I have found picard under conda: https://anaconda.org/bioconda/picard

I have tried to install MAESTRO( https://anaconda.org/liulab-dfci/maestro) conda: conda install -c liulab-dfci maestro。 But it reports 
![image](https://user-images.githubusercontent.com/34993687/107010899-e6075c80-67d1-11eb-86d5-dd44eef446e8.png)

**Comment by crazyhottommy** [comment]
oh, can you do 

```bash
$ conda config --add channels defaults
$ conda config --add channels liulab-dfci
$ conda config --add channels bioconda
$ conda config --add channels conda-forge
# To make the installation faster, we recommend using mamba
$ conda install mamba -c conda-forge
$ mamba create -n MAESTRO maestro=1.3.2 -c liulab-dfci
# Activate the environment
$ conda activate MAESTRO
```

**Comment by f6v** [comment]
@jphe Mac OS isn't supported, only Linux.
<img width="214" alt="image" src="https://user-images.githubusercontent.com/13019221/108551628-812f2480-72f0-11eb-8e32-b94ecaaa6451.png">
