### ISSUE TITLE
Installation error with conda 

### ISSUE THREAD

**Issue by preetida** [liulab-dfci/MAESTRO#119]
Hi, 
I am following the conda instruction for setting up MAESTRO. 
My install failed with below error. 

I can think of **conda-build version : not installed** might be issue but not sure? 
Whats the alternate ? 
`mamba create -n MAESTRO maestro=1.3.2 -c liulab-dfc`
`# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/pjb40/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/pjb40/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 882, in exception_converter
        raise e
      File "/home/pjb40/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 876, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/home/pjb40/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 835, in _wrapped_main
        result = do_call(args, p)
      File "/home/pjb40/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 720, in do_call
        exit_code = create(args, parser)
      File "/home/pjb40/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 624, in create
        return install(args, parser, "create")
      File "/home/pjb40/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 572, in install
        downloaded = transaction.prompt(
    RuntimeError: Found incorrect download. Aborting

`$ /home/pjb40/miniconda3/bin/mamba create -n MAESTRO maestro=1.3.2 -c liulab-dfci`

  environment variables:
CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/pjb40/miniconda3/bin/conda
             CONDA_PREFIX=/home/pjb40/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/pjb40/miniconda3/bin/python
               CONDA_ROOT=/home/pjb40/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 GEM_PATH=/usr/local/rvm/gems/ruby-2.4.9:/usr/local/rvm/gems/ruby-2.4.9@global
                  MANPATH=/n/app/lmod/lmod/share/man::
               MODULEPATH=/n/app/lmod/lmod/modulefiles/Linux:/n/app/lmod/lmod/modulefiles/Core
                     PATH=/home/pjb40/homework/Nextflow/nf-gwas-pipeline:/n/scratch3/groups/hsph
                          /hbc/pjb40/scratch/pkgs/nodejs0.10.30/bin:/n/scratch3/groups/hsph/hbc/
                          pjb40/scratch/pkgs/subread-2.0.1-Linux-x86_64/bin/featureCounts:/n/scr
                          atch3/groups/hsph/hbc/pjb40/scratch/pkgs:/home/pjb40/tools/gatk-4.1.7.
                          0:/n/scratch3/groups/hsph/hbc/pjb40/scratch/backup/pjb40/bustools:/n/s
                          cratch3/groups/hsph/hbc/pjb40/scratch/backup/pjb40/kallisto:/n/scratch
                          3/groups/hsph/hbc/pjb40/scratch/pkgs/cellranger-5.0.1:/n/scratch3/grou
                          ps/hsph/hbc/pjb40/scratch/covid/software/cellranger-3.1.0:/n/cluster/b
                          in:/opt/singularity/bin:/home/pjb40/miniconda3/bin:/home/pjb40/homewor
                          k/Nextflow/nf-gwas-pipeline:/n/scratch3/groups/hsph/hbc/pjb40/scratch/
                          pkgs/nodejs0.10.30/bin:/n/scratch3/groups/hsph/hbc/pjb40/scratch/pkgs/
                          subread-2.0.1-Linux-x86_64/bin/featureCounts:/n/scratch3/groups/hsph/h
                          bc/pjb40/scratch/pkgs:/home/pjb40/tools/gatk-4.1.7.0:/n/scratch3/group
REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
             rvm_bin_path=/usr/local/rvm/bin
                 rvm_path=/usr/local/rvm

     active environment : base
    active env location : /home/pjb40/miniconda3
            shell level : 1
       user config file : /home/pjb40/.condarc
 populated config files : /home/pjb40/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/pjb40/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/liulab-dfci/linux-64
                          https://conda.anaconda.org/liulab-dfci/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
package cache : /home/pjb40/miniconda3/pkgs
                          /home/pjb40/.conda/pkgs
       envs directories : /home/pjb40/miniconda3/envs
                          /home/pjb40/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/3.10.0-1062.el7.x86_64 centos/7.7.1908 glibc/2.17
                UID:GID : 172693:2172693
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.`

**Comment by crazyhottommy** [comment]
that's something new to me. I just installed 1.3.2 on two clusters, and they all worked fine.
Are you able to install other tools?

```bash
mamba create -n lisa2 -c liulab-dfci lisa2
```
