### ISSUE TITLE
Bug: Let reticulate find the current Python

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#12]
If users use MAESTRO for the first time or more accurately use "reticulate" package through ATACCalculateGenescore script for the first time, they will be prompted to decide whether "reticulate" should install an independent miniconda environment by itself. 
```
No non-system installation of Python could be found.
Would you like to download and install Miniconda?
Miniconda is an open source environment management system for Python.
See https://docs.conda.io/en/latest/miniconda.html for more details.

Would you like to install Miniconda? [Y/n]: n
```

Assuming users are utilizing conda/miniconda version of MAESTRO for their analysis, they should stick to the python in that environment, so answer "n". This has to be done just once. We'd better describe it in our tutorial otherwise users may have a lot of trouble later on if they accidentally answer "Y" to the above question. See the discussion regarding this in https://github.com/rstudio/reticulate/issues/607.

The code related to the issue is

https://github.com/liulab-dfci/MAESTRO/blob/92b1d3f89f8e2bd0e02dd0ce7d6786699de51531/R/ATACCalculateGenescore.R#L29-L30

**Comment by DongqingSun96** [comment]
Hi Tao,

Thanks for reporting the bug. We have add some notes in the [tutorial](https://github.com/liulab-dfci/MAESTRO/blob/master/example/ATAC_infrastructure_10x/ATAC_infrastructure_10x.md) in case users may have some trouble when they use `ATACCalculateGenescore` function. 

If there's any other problem, please let me know.

Thanks!
Dongqing

**Comment by taoliu** [comment]
Should we suggest users use `use_condaenv` instead of `use_python`? 

https://cran.r-project.org/web/packages/reticulate/vignettes/versions.html
