### ISSUE TITLE
Error Calls: ATACRunSeurat ... CreateSeuratObject.default -> CreateSeuratObject -> CreateSeuratObject.Assay

### ISSUE THREAD

**Issue by jphe** [liulab-dfci/MAESTRO#121]
Hi,

Thanks for update MAESTRO, I have installed the latest MAESTRO but it reports an error:

Seems it is Seurat problem? My Seurat version is 3.99

> Registered S3 method overwritten by 'GGally':
  method from
  +.gg   ggplot2
Registered S3 methods overwritten by 'SeuratObject':
  method                     from
  $.JackStrawData            Seurat
  $.Seurat                   Seurat
  $.SeuratCommand            Seurat
  $<-.Seurat                 Seurat
  [.Assay                    Seurat
  [.DimReduc                 Seurat
  [.Seurat                   Seurat
  [.SeuratCommand            Seurat
  [.SpatialImage             Seurat
  [[.Assay                   Seurat
  [[.DimReduc                Seurat
  [[.Seurat                  Seurat
  levels<-.Seurat            Seurat
  .DollarNames.JackStrawData Seurat
  .DollarNames.Seurat        Seurat
  .DollarNames.SeuratCommand Seurat
  as.list.SeuratCommand      Seurat
  as.logical.JackStrawData   Seurat
  dim.Assay                  Seurat
  dim.DimReduc               Seurat
  dim.Neighbor               Seurat
  dim.Seurat                 Seurat
  dim.SpatialImage           Seurat
  dimnames.Assay             Seurat
  dimnames.DimReduc          Seurat
  dimnames.Seurat            Seurat
  droplevels.Seurat          Seurat
  length.DimReduc            Seurat
  levels.Seurat              Seurat
  merge.Assay                Seurat
  merge.DimReduc             Seurat
  merge.Seurat               Seurat
  names.DimReduc             Seurat
  names.Seurat               Seurat
  print.DimReduc             Seurat
  subset.Assay               Seurat
  subset.DimReduc            Seurat
  subset.Seurat              Seurat
  subset.SpatialImage        Seurat
Registered S3 method overwritten by 'cli':
  method     from
  print.boxx spatstat
Warning message:
replacing previous import 'GenomicRanges::.__C__GenomicRanges_OR_GenomicRangesList' by 'rtracklayer::.__C__GenomicRanges_OR_GenomicRangesList' when loading 'BSgenome'
Warning: Feature names cannot have underscores ('_'), replacing with dashes ('-')
Error in `[[<-`(`*tmp*`, "orig.ident", value = idents) :
  [[<- defined for objects of type "S4" only for subclasses of environment
Calls: ATACRunSeurat ... CreateSeuratObject.default -> CreateSeuratObject -> CreateSeuratObject.Assay
Execution halted
[Thu Mar 11 20:33:25 2021]
Error in rule scatac_analysis:
    jobid: 5
    output: Result/Analysis/10X_PBMC_10k_DiffPeaks.tsv, Result/Analysis/10X_PBMC_10k_cluster.png, Result/Analysis/10X_PBMC_10k.PredictedTFTop10.txt, Result/Analysis/10X_PBMC_10k_cell_cluster.txt
    shell:
        Rscript /public/home/jphe/anaconda3/envs/scanpy/lib/python3.6/site-packages/MAESTRO-1.4.0-py3.6.egg/MAESTRO/R/scATACseq_pipe.R --peakcount ../QC/10X_PBMC_10k_filtered_peak_count.h5 --rpmatrix 10X_PBMC_10k_gene_score.h5 --species GRCh38 --prefix 10X_PBMC_10k --annotation True --method both --signature human.immune.CIBERSORT --gigglelib /public/home/jphe/ATACseq/hg38/scATAC/PBMC/giggle.all --fragment ../minimap2/fragments_corrected_count.tsv.gz --outdir Result/Analysis --thread 10
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /public/home/jphe/ATACseq/hg38/scATAC/PBMC/MEASTRO/PBMC_10k_MAESTRO_bam/.snakemake/log/2021-03-11T202306.024792.snakemake.log

**Comment by jphe** [comment]
Attached is the details for the log file.

[10X_PBMC_10k.txt](https://github.com/liulab-dfci/MAESTRO/files/6123212/10X_PBMC_10k.txt)

**Comment by crazyhottommy** [comment]
you should install Seurat V4.0

**Comment by crazyhottommy** [comment]
if you installed the latest v1.4 MAESTRO, Seurat will be https://github.com/liulab-dfci/MAESTRO/blob/master/conda/MAESTRO/meta.yaml#L42
