### ISSUE TITLE
RNAAnnotateTranscriptionFactor - return all tfs?

### ISSUE THREAD

**Issue by f6v** [liulab-dfci/MAESTRO#124]
`RNAAnnotateTranscriptionFactor` has a `top.tf` argument. However, is there a way to return the whole list?

Thanks!

**Comment by crazyhottommy** [comment]
Hi, can you try a large top.tf number? @baigal628 is it possible to return the whole list?

**Comment by baigal628** [comment]
Hi,

After running LISA2 with RNAAnnotateTranscriptionFactor(), you will get a list of predicted TFs for each cluster under {project}.lisa/ folder. The file name should be {cluster_id}.txt.lisa.tsv. Or you can also find a file called {project}_lisa.txt in your working directory which summarized all the common predicted TFs for each cluster.
