### ISSUE TITLE
Error in ATACAnnotateTranscriptionFactor function

### ISSUE THREAD

**Issue by strawberry789** [liulab-dfci/MAESTRO#125]
When I run the ATACAnnotateTranscriptionFactor function, I get the following error:

Error in read.table(paste0(outputBed, ".result.xls"), sep = "\t", row.names = NULL, : no lines available in input

I'm using Maestro v. 1.2.2 and have downloaded the giggle.all.tar.gz file

Also, do I not need to specify the giggle file as mouse if I'm analyzing mouse data?  The giggle.all folder includes both mouse and human giggle data.

**Comment by crazyhottommy** [comment]
Hi, it seems you did not get any results for the giggle command and get an empty file, you can specify `organism = "GRCm38` and retry it.
