### ISSUE TITLE
The 'percent.mito' and 'percent.ercc' are actually ratio not percentage.

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#129]
Codes are here

https://github.com/liulab-dfci/MAESTRO/blob/2c87d7a624745cc7e4fefc202042b221844e722c/R/RNARunSeurat.R#L69-L70

If we want to call the value 'percent', please multiply the value with 100.

**Comment by crazyhottommy** [comment]
fixed in the MAESTRO 1.5.0
