### ISSUE TITLE
Test file for ATAC-seq pipeline missing 

### ISSUE THREAD

**Issue by mudappathir** [liulab-dfci/MAESTRO#130]
Hi,

I just installed MAESTRO and wanted to run the pipeline using test files provided for scRNA and scATAC seq. But the file location http://cistrome.org/~galib/atac_pbmc_500_v1_fastqs_sampling.tar.gz is missing. Please help.

**Comment by baigal628** [comment]
Could you please try again? It should be able to download now.

**Comment by mudappathir** [comment]
Yes it is working now. Thank you very much for quick response.
