### ISSUE TITLE
RNARunSeurat error at RunPCA stage

### ISSUE THREAD

**Issue by mudappathir** [liulab-dfci/MAESTRO#131]
Hi,
I am trying to perform analysis on the test scRNA seq data provided.  I could successfully run the snakemake pipeline. In R I get following error for:
pbmc.RNA.res <- RNARunSeurat(inputMat = pbmc.gene,
                               project = "10X_PBMC_1k",
                               orig.ident = NULL,
                               min.c = 10,
                               min.g = 100,
                               mito = TRUE,
                               mito.cutoff = 0.05,
                               variable.genes = 2000,
                               organism = "GRCh38",
                               dims.use = 1:15,
                               cluster.res = 0.6,
                               only.pos = FALSE,
                               genes.test.use = "presto",
                               genes.cutoff = 1e-05,
                               genes.pct = 0.1,
                               genes.logfc = 0.25)

**** Error *****
Check the mitochondria and spike-in percentage ...
Normalization and identify variable genes ...
Performing log-normalization
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating gene variances
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Calculating feature variances of standardized and clipped values
0%   10   20   30   40   50   60   70   80   90   100%
[----|----|----|----|----|----|----|----|----|----|
**************************************************|
Regressing out nCount_RNA, percent.mito, percent.ercc
  |======================================================================| 100%
Centering and scaling data matrix
  |======================================================================| 100%
PCA analysis ...
Error in irlba(A = t(x = object), nv = npcs, ...) :
  max(nu, nv) must be strictly less than min(nrow(A), ncol(A))
In addition: Warning messages:
1: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  at  -0.8646
2: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  radius  0.0003805
3: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  all data on boundary of neighborhood. make span bigger
4: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  pseudoinverse used at -0.8646
5: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  neighborhood radius 0.019506
6: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  reciprocal condition number  1
7: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  zero-width neighborhood. make span bigger
8: In simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :
  There are other near singularities as well. 0.031008

-------------------------------

Should I mention any parameter for npcs to run PCA. Please advise.

**Comment by baigal628** [comment]
Hi,

It seems like there are less than 50 cells in the count matrix. Could you please change the mito.cutoff to 0.2 for the test data? 0.05 could be too strict so the cells are filtered out! 

Thanks.

**Comment by mudappathir** [comment]
Yes that works. Thank you.
