### ISSUE TITLE
Cannot download giggle.all.tar.gz

### ISSUE THREAD

**Issue by WWJiaxuan** [liulab-dfci/MAESTRO#133]
Hi,

Thanks very much for the user-friendly package!

I just encountered a problem that I couldn't download giggle.all.tar.gz. It seems that the link didn't work, and I am not sure where and which one to download from Cistrome (since there're too many options...). Could you please suggest how I can deal with it?

Thanks in advance and looking forward to your reply!

**Comment by crazyhottommy** [comment]
Hi, it is at http://cistrome.org/~galib/giggle.all.tar.gz. the link is updated at v1.2.0 change log in the README.

Thanks!

**Comment by WWJiaxuan** [comment]
Hi,

Thanks very much for your prompt reply! Yes, I have clicked the above link and also the link in the README many times, but unfortunately no response. Is there any other way to download it?

**Comment by crazyhottommy** [comment]
on command line:
```bash
curl -O http://cistrome.org/~galib/giggle.all.tar.gz 
```

**Comment by WWJiaxuan** [comment]
It started downloading. Thanks again for your help and the great package!

**Comment by crazyhottommy** [comment]
do not hesitate to open github issues if you have more questions.

**Comment by yuxuth** [comment]
Hi Tommy @crazyhottommy ,

Looks like the giggle.all.tar.gz link is broken (http://cistrome.org/~galib/giggle.all.tar.gz ). Get 404 error. 

```
Not Found
The requested URL /~galib/giggle.all.tar.gz was not found on this server.
```

Would you please take a look?

Thanks!

**Comment by yuxuth** [comment]
It works now! 
Thanks
