### ISSUE TITLE
Unable to download the mapindex file for human from http://cistrome.org/~galib/Refdata_scRNA_MAESTRO_GRCh38_1.2.2.tar.gz

### ISSUE THREAD

**Issue by llk578496** [liulab-dfci/MAESTRO#138]
Hi, we would like to download the mapindex file for human, but it returns the following error message:

'''
Not Found
The requested URL /~galib/Refdata_scRNA_MAESTRO_GRCh38_1.2.2.tar.gz was not found on this server.

Apache/2.4.29 (Ubuntu) Server at cistrome.org Port 80
'''
Please kindly advise.
Thank you very much.

Eddie Lee

**Comment by baigal628** [comment]
Hi!

I just moved the reference genomes but will update the new link with the next release! Please find out here: 

http://cistrome.org/~galib/MAESTRO/references/scRNA/Refdata_scRNA_MAESTRO_GRCh38_1.2.2.tar.gz

Thanks!

**Comment by llk578496** [comment]
Thank you very much!
