### ISSUE TITLE
Cannot install v1.4.0

### ISSUE THREAD

**Issue by llk578496** [liulab-dfci/MAESTRO#139]
Hi, sorry to bother you again.

We followed the command lines to install the MAESTRO with miniconda:

'''
$ wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
$ bash Miniconda3-latest-Linux-x86_64.sh

$ conda config --add channels defaults
$ conda config --add channels liulab-dfci
$ conda config --add channels bioconda
$ conda config --add channels conda-forge
$ conda install mamba -c conda-forge
$ mamba create -n MAESTRO maestro=1.4.0 -c liulab-dfci
$ conda activate MAESTRO
'''

but we check the version by $MAESTRO -v
it returns v1.3.1

May we know is there any method to install the MAESTRO with v1.4.0 ? 

Please advise. Thank you very much!

Eddie

**Comment by baigal628** [comment]
Hi Eddie!

Sorry that there was a bug in the version. You should have installed version 1.4.0 although it appeared as v1.3.1. We will fix that following the next release. Thanks!
