### ISSUE TITLE
Bug: scATAC_genescore.py and ATACCalculateGenescore.R can't handle peaks from unusual chromosomes

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#14]
When peaks are from unusual chromosomes such as "chr11_KI270721v1_random", scATAC_genescore.py and ATACCalculateGenescore.R can't correctly split the peak name such as "chr11_KI270721v1_random_12345_67890" to find the chromosome name, start and end positions since it will use "_" as the separator:

https://github.com/liulab-dfci/MAESTRO/blob/4af5c118f791a8ffe0f242f0ebea7fee014ffb53/MAESTRO/scATAC_genescore.py#L96-L98

Please use `rsplit("_",maxsplit=2)` instead. Here is an example:

```
>>> a="chr11_KI270721v1_random_12345_67890"
>>> a.split("_") # this will incorrectly split the chromosome name
['chr11', 'KI270721v1', 'random', '12345', '67890']
>>> a.rsplit("_",maxsplit=2) # this will give exactly three values
['chr11_KI270721v1_random', '12345', '67890']
```

**Comment by chenfeiwang** [comment]
We have updated the bug in the latest version of MAESTRO.
