### ISSUE TITLE
Can't install maestro=1.5.0

### ISSUE THREAD

**Issue by zuoyi93** [liulab-dfci/MAESTRO#144]
Hi,

I experienced an error while installing the MAESTRO version 1.5.0. Specifically, when I ran `mamba create -n MAESTRO maestro=1.5.0 -c liulab-dfci`, it gave me the following error message:

<img width="466" alt="Screen Shot 2021-07-19 at 7 45 43 AM" src="https://user-images.githubusercontent.com/25957920/126161717-1c38ea1e-8f35-452e-b823-748c33c320f2.png">

Any idea what went wrong?

I'm working on a Mac OS machine and all previous steps look right.

Thanks in advance!

Yi

**Comment by crazyhottommy** [comment]
Hi Yi, 
MAESTRO is only available in linux machines, not in mac OS.

**Comment by zuoyi93** [comment]
Thanks for your prompt reply.
