### ISSUE TITLE
conflict between scrna_parser and scrna_validator

### ISSUE THREAD

**Issue by yxian9** [liulab-dfci/MAESTRO#147]
Hi,

I try to use the `MAESTRO scrna-init` on Dropseq platform. 

when specify the '--platform dropseq' in the` MAESTRO scrna-init`. I got error message as 

`AttributeError: 'Namespace' object has no attribute 'input_path'`

I found The [`scrna_validator`](https://github.com/liulab-dfci/MAESTRO/blob/a0baabec4ffb538013385f8fb214a12b0fcfa50d/MAESTRO/MAESTRO_ParameterValidate.py#L92
)  require 'input_path', which has been removed in the  [`scrna_parser`](https://github.com/liulab-dfci/MAESTRO/blob/a0baabec4ffb538013385f8fb214a12b0fcfa50d/MAESTRO/MAESTRO_PipeInit.py#L174
), which may be the issue.

Thanks!

**Comment by crazyhottommy** [comment]
Thanks @yuxuth for reporting. The recent multi-sample scRNAseq and scATACseq MAESTRO version does not support DropSeq data I believe since it has one fastq file for one cell.  @baigal628 can you please confirm?

**Comment by yxian9** [comment]
I see.  No worry. I'm able to manually modify the snakemake file to move on. 
Thanks.
