### ISSUE TITLE
Question: Can we do TF annotation without doing cell annotation?

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#15]
In some cases, we do not know the actual cell types, or we do not know the signature genes of possible cell types, so we'd like to skip cell-type annotation step, and plan to identify the driver TFs for each cluster. Can we do that? I am asking this since according to the tutorial, the regulation potentials (RP, or gene scores) are only to be included in the 'cell type annotation' step, but RPs are needed in the TF identification step.

**Comment by chenfeiwang** [comment]
Thanks for the suggestion. In the latest version of MAESTRO, we have added a function named ATACAttachGenescore, which can attach the RP matrix into the object without doing cell-type annotation, then users can perform the downstream TF analysis. We have also updated the tutorials accordingly.
