### ISSUE TITLE
Use bedtools map instead of intersect in scATAC_10x_PeakCount?

### ISSUE THREAD

**Issue by jeremymsimon** [liulab-dfci/MAESTRO#157]
Thanks for assembling this nice workflow!

I was curious about the step in your scATAC analysis where you take your peaks file, fragments files, and compute a cells x peaks matrix of overlaps. It looks like this primarily happens [here](https://github.com/liulab-dfci/MAESTRO/blob/master/MAESTRO/scATAC_10x_PeakCount.py). 

If I understand your code correctly, it looks like you do the following (please correct me if I'm mistaken):
- Filter barcodes to keep only those with at least 1000 fragments (by default)
- Divide up the fragments file, one per (passing) barcode
- Run `bedtools intersect -c` to count the number of overlaps with each peak in the peak file
- Assemble counts from all cells into a matrix

Perhaps I'm missing it in your code, but `bedtools intersect -c` won't use the read support value (column 5) in the fragments file. Wouldn't `bedtools map` be more appropriate here, such that you take the sum of all overlapping read support values?

For example, if my fragments file has:
```
chr1    10157   10186   CAACCAAAGTTCTCCC        15
chr1    10213   10242   CAACCAAAGTTCTCCC        3
```

and my peaks file has:
```
chr1    9955    10355
```

Wouldn't I want the resulting count to be:
```
chr1    9955    10355       18
```

instead of 
```
chr1    9955    10355       2
```

**Comment by crazyhottommy** [comment]
I believe the 15 and 3 are the number of fragments with exactly the same location (duplicates). 
In single-cell ATACseq, you will have only one copy of the fragment ( we have two copies of DNA, but the fragmentation will unlikely result in the same fragment in two chromosomes).
So we count them as 1.

**Comment by jeremymsimon** [comment]
Got it, thanks @crazyhottommy!
