### ISSUE TITLE
Enhancement: Suggestions on MAESTRO/R/ATACRunSeurat.R

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#19]
If we look at MAESTRO/R/ATACRunSeurat.R script, it includes many of Seurat functions, such as RunLSI, FindCluster, and RunUMAP. However, the parameters for these functions are mainly fixed with only few tunable parameters for users. How can users tweak the parameter such as n.neighbors or min.dist for UMAP with this script, or the maximum number of components from LSI (n=50 is fixed)? My suggestion is to break this big script into at least three modules -- LSI, UMAP, and DE, and provide more options!

**Comment by chenfeiwang** [comment]
In the latest version of MAESTRO, we have support parsing all parameters of the above Seurat functions into ATACRunSeurat directly. Please check the updated descriptions of this function.
