### ISSUE TITLE
Bug: bdg to bw in Snakemake

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#2]
The current implementation has a potential problem. The `bedtools intersect` with `-f 1.00` will get rid of the region that is not ENTIRELY included in the `chr_limit` file. It would be more reasonable to **clip** instead of **discarding** the whole region. 

https://github.com/liulab-dfci/MAESTRO/blob/ffdfffe0a28bf8e42cf86a63697d0ab40b78ade7/MAESTRO/Snakemake/scATAC/Snakefile#L637-L651

Check my gist: https://gist.github.com/taoliu/2469050

**Comment by chenfeiwang** [comment]
Thank you Tao! In the latest version of MAESTRO, we have removed the function of CEAS, and the bdg to bw is removed from the workflow. 

We will use the clipping instead of removing the whole region if future implementation needs this function.
