### ISSUE TITLE
Question: Any plan to upgrade R to 3.6?

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#20]
Currently, R 3.5 is specifically required. Any reason that we should keep using the old version? Or is there any plan to upgrade? The reason why I asked is that the latest Bioconductor (3.10) requires R 3.6.

https://github.com/liulab-dfci/MAESTRO/blob/da64dcb990521722bab08e4454d76ac6f027750e/conda/MAESTRO/meta.yaml#L32

**Comment by chenfeiwang** [comment]
The latest MAESTRO works for R 3.6.1.
