### ISSUE TITLE
Bug: incorrect use of MACS2 -n option

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#3]
As shown in the current code to invoke macs2:

https://github.com/liulab-dfci/MAESTRO/blob/ffdfffe0a28bf8e42cf86a63697d0ab40b78ade7/MAESTRO/Snakemake/scATAC/Snakefile#L138-L152

The option '-n' contains a folder structure. This is not a recommended way to specify an output directory of macs2. Please use '--outdir' instead and keep the '-n'  simple such as:

`name = config["outprefix"] + "_all"`

and

`macs2 callpeak -g hs --outdir Result/Analysis -n {params.name} -B -q 0.05 --nomodel --extsize=50 --SPMR -t {input.bam}`

The issue is also related to other places in this Snakemake file where MACS2 is invoked.

**Comment by chenfeiwang** [comment]
Thanks for this suggestion, the snakemake workflow has been updated.

**Comment by taoliu** [comment]
Fixed in 92b1d3f
