### ISSUE TITLE
Bug: Bugs of relative pathes in the MAESTRO scrna-/scatac-init scripts and Errors in Tutorial 

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#33]
The version of MAESTRO: v1.1.0

Command line bugs:

1. If `--fastq-dir` ends with /, the `snakemake` cmd will give a ‘double /’ warning.
2. If `--fastq-dir` is a relative path, it won’t work since this relative path will be added to the config file in a new child directory; the same problem can be found for the option for whitelist file.

Tutorial errors:

1. The instruction, there is no  `--directory`  option but `-d`.
2. The assembly names `GRCh38` or `GRCm38` are not `species` names!
3. Please do not hardcode path names in instruction.
4. Errors in the scRNA instruction: the download link for the STAR index only contains human data. The RSEM library download link is pointing to giggle download.

**Comment by taoliu** [comment]
Also, `pysam` has to be added to list of dependencies of MAESTRO conda package.

**Comment by DongqingSun96** [comment]
Thank you so much for reporting these bugs. We have updated MAESTRO and enable it to support relative path and to be compatible with directory path with or without '/'. Please install the latest version and let us know if there's any problem. The mentioned errors in the tutorial have also been corrected. As for `pysam`, it has been one of the dependencies of RSeQC, so we didn't add it to our dependencies separately.
