### ISSUE TITLE
Multi-sample analysis!

### ISSUE THREAD

**Issue by TheSallyGardens** [liulab-dfci/MAESTRO#39]
Hi!
A very good tool.
I now have five scATAC samples.How do I merge multiple samples?

**Comment by TheSallyGardens** [comment]
Does the species support hg19?

**Comment by crazyhottommy** [comment]
Hi @TheSallyGardens we are working on multiple-sample processing for scATACseq data. will update when we are ready for a release. Thanks for your patience.

**Comment by QiangTU** [comment]
Is the multi-sample function supported now? Thanks!

**Comment by crazyhottommy** [comment]
we will release a new version supporting multi-sampling scATACseq in 2 weeks. Thanks for your patience. I will post here and close this issue once we have it out.

**Comment by crazyhottommy** [comment]
You can try v1.3.1 for multi-sample scATACseq now. It has been a while.
