### ISSUE TITLE
Feature request: Add recipe on bioconda

### ISSUE THREAD

**Issue by mjsteinbaugh** [liulab-dfci/MAESTRO#4]
Hi @liulab-dfci, I'm interested in trying out MAESTRO, and the Dockerfile recipe works great. One thing I noticed is that the conda recipe is currently managed under a custom channel (see https://anaconda.org/liulab-dfci/maestro). I was wondering if it would be possible to submit the recipe to [bioconda](https://bioconda.github.io/), which makes developing other recipes that depend on MAESTRO easier to manage.

Best,
Mike

**Comment by DongqingSun96** [comment]
Hi @mjsteinbaugh, thanks for your suggestion. We're planning to submit MAESTRO to bioconda in the next few months. Please continue to follow up our update. Thanks!

**Comment by mjsteinbaugh** [comment]
Awesome thanks @DongqingSun96 !
