### ISSUE TITLE
Dockerfile recipe error

### ISSUE THREAD

**Issue by mjsteinbaugh** [liulab-dfci/MAESTRO#5]
I'm currently hitting this error on the last step of the `Dockerfile` recipe:

```
Step 10/10 : RUN cd /root/Annotation && tar -xzvf rabit.tar.gz && tar -xzvf giggle.tar.gz && rm rabit.tar.gz && rm giggle.tar.gz
 ---> Running in a935b7a7a681
tar (child): rabit.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
The command '/bin/sh -c cd /root/Annotation && tar -xzvf rabit.tar.gz && tar -xzvf giggle.tar.gz && rm rabit.tar.gz && rm giggle.tar.gz' returned a non-zero code: 2
```

**Comment by DongqingSun96** [comment]
Hi. Seems like you're building the docker image from scratch. You can pull the image using `docker pull winterdongqing/maestro:1.0.1` directly. If you want to build the image by yourself, you can download the [Rabit index](http://cistrome.org/~chenfei/MAESTRO/rabit.tar.gz) and [giggle index](http://cistrome.org/~chenfei/MAESTRO/giggle.tar.gz) from Cistrome website to the folder which stores the `Dockerfile`.
Please let me know if there's any problem.
