### ISSUE TITLE
Why I can't open the HTML report

### ISSUE THREAD

**Issue by Taozimk** [liulab-dfci/MAESTRO#52]
Several sets of data were tested, and it was very convenient.
When I open HTML report, but I can't see any  contents of the  report only sample information. 
Is there anything I haven't noticed?
![image](https://user-images.githubusercontent.com/26337757/90726581-8b964480-e2f4-11ea-8627-9feadb315d0e.png)

**Comment by crazyhottommy** [comment]
which version of MAESTRO are you using? I have run with the most recent release v 1.2.1, and the HTML report functions properly.
