### ISSUE TITLE
install_github("liulab-dfci/MAESTRO") error

### ISSUE THREAD

**Issue by ChangliangWang** [liulab-dfci/MAESTRO#53]
Dear Tao,

When I ran install_github("liulab-dfci/MAESTRO"), I encountered the below error. Have you ever encountered the same error? 

Error: Failed to install 'unknown package' from GitHub:
Failed to connect to api.github.com port 443: Connection refused

Thanks very much for your help.

Best regards,
Leon.

**Comment by ChangliangWang** [comment]
The unknown package might be the 'presto'. Is MAESTRO based on '**immunogenomics/presto**' (https://github.com/immunogenomics/presto).

Thanks very much for your help.

Best regards,
Leon.

**Comment by ChangliangWang** [comment]
The error is due to internet problem. I have run the command several times. Sometimes, it worked as the figure shows.
![image](https://user-images.githubusercontent.com/25944188/91373293-9ac34800-e848-11ea-825c-9aa2a183fb71.png)

**Comment by taoliu** [comment]
@ChangliangWang  I recommend you install MAESTRO through conda. The conda package includes MAESTRO R codes so there is no need to do devtools install again.

**Comment by ChangliangWang** [comment]
Hi Tao,

Thanks very much for your suggestion. I have tried one day to install the package by devtools. Unfortunately, few minutes ago, I failed again. I will try to install it by conda. Big thanks.

Have a nice day.

Best wishes,
Changliang.

________________________________
发件人: Tao Liu (τν) <notifications@github.com>
发送时间: 2020年8月28日 2:47
收件人: liulab-dfci/MAESTRO <MAESTRO@noreply.github.com>
抄送: Wang Changliang <yb67610@connect.um.edu.mo>; Mention <mention@noreply.github.com>
主题: Re: [liulab-dfci/MAESTRO] install_github("liulab-dfci/MAESTRO") error (#53)


@ChangliangWang<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ChangliangWang&d=DwMCaQ&c=KXXihdR8fRNGFkKiMQzstu-8MbOxd1NuZkcSBymGmgo&r=bhPcwygvMRH7vWVpUUxVrQ&m=GivIOEmn3fTsiLZ5iczHwiMHEFmxKYeDgoF2sUf4gTo&s=eboNJbjTIqGAfOw3Q4KjICqXYxzTkm5mHiJFV8MTYhg&e=> I recommend you install MAESTRO through conda. The conda package includes MAESTRO R codes so there is no need to do devtools install again.

―

**Comment by ChangliangWang** [comment]
Hi Tao,

I have encountered the below problem, which might be caused by my poor network again,(Do you think this problem is due to network):
    Traceback (most recent call last):
      File "/share/home/wangchangliang/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/share/home/wangchangliang/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 814, in exception_converter
        raise e
      File "/share/home/wangchangliang/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 808, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/share/home/wangchangliang/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 773, in _wrapped_main
        result = do_call(args, p)
      File "/share/home/wangchangliang/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 667, in do_call
        exit_code = create(args, parser)
      File "/share/home/wangchangliang/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 568, in create
        install(args, parser, 'create')
      File "/share/home/wangchangliang/miniconda3/lib/python3.8/site-packages/mamba/mamba.py", line 353, in install
        index = get_index(channel_urls=index_args['channel_urls'],
      File "/share/home/wangchangliang/miniconda3/lib/python3.8/site-packages/mamba/utils.py", line 69, in get_index
        is_downloaded = dlist.download(True)
    RuntimeError: Multi-download failed.

Best wishes,
Changliang.

________________________________
发件人: Tao Liu (τν) <notifications@github.com>
发送时间: 2020年8月28日 2:47
收件人: liulab-dfci/MAESTRO <MAESTRO@noreply.github.com>
抄送: Wang Changliang <yb67610@connect.um.edu.mo>; Mention <mention@noreply.github.com>
主题: Re: [liulab-dfci/MAESTRO] install_github("liulab-dfci/MAESTRO") error (#53)


@ChangliangWang<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ChangliangWang&d=DwMCaQ&c=KXXihdR8fRNGFkKiMQzstu-8MbOxd1NuZkcSBymGmgo&r=bhPcwygvMRH7vWVpUUxVrQ&m=GivIOEmn3fTsiLZ5iczHwiMHEFmxKYeDgoF2sUf4gTo&s=eboNJbjTIqGAfOw3Q4KjICqXYxzTkm5mHiJFV8MTYhg&e=> I recommend you install MAESTRO through conda. The conda package includes MAESTRO R codes so there is no need to do devtools install again.

―

**Comment by ChangliangWang** [comment]
Dear Tao,

Finally, I have installed the package using install.github, successfully. The package is really cool. Thanks very much for your efforts on the package.

BTW, I have encountered another problem. When I using conda search 'lisa' tool, there is no image for the tool. So, I wonder how you install the  tool successfully. Do you have any suggestion to install 'lisa'.

Thanks very much for your help.

Best Regards,
Leon.

________________________________
发件人: Tao Liu (τν) <notifications@github.com>
发送时间: 2020年8月28日 2:47
收件人: liulab-dfci/MAESTRO <MAESTRO@noreply.github.com>
抄送: Wang Changliang <yb67610@connect.um.edu.mo>; Mention <mention@noreply.github.com>
主题: Re: [liulab-dfci/MAESTRO] install_github("liulab-dfci/MAESTRO") error (#53)


@ChangliangWang<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ChangliangWang&d=DwMCaQ&c=KXXihdR8fRNGFkKiMQzstu-8MbOxd1NuZkcSBymGmgo&r=bhPcwygvMRH7vWVpUUxVrQ&m=GivIOEmn3fTsiLZ5iczHwiMHEFmxKYeDgoF2sUf4gTo&s=eboNJbjTIqGAfOw3Q4KjICqXYxzTkm5mHiJFV8MTYhg&e=> I recommend you install MAESTRO through conda. The conda package includes MAESTRO R codes so there is no need to do devtools install again.

―
