### ISSUE TITLE
How to generate those QC metrics plots?

### ISSUE THREAD

**Issue by yuewangpanda** [liulab-dfci/MAESTRO#54]
Hi, 

Thank you for this great work! I just have one question when I go through the Galleries & Tutorials. For the scRNA-seq example, after the RNARunSeurat() function, you use str() to check those features. How to plot those figures below the line of str(pbmc.RNA.res$RNA)?

Thanks,
Frank

**Comment by DongqingSun96** [comment]
Hi @yuewangpanda, after running `RNARunSeurat()` successfully, the three figures named as `*.spikein.png`, `*_PCElbowPlot.png`, `*_cluster.png` will be stored in your current working directory. You can check if they exist.

**Comment by yuewangpanda** [comment]
> Hi @yuewangpanda, after running `RNARunSeurat()` successfully, the three figures named as `*.spikein.png`, `*_PCElbowPlot.png`, `*_cluster.png` will be stored in your current working directory. You can check if they exist.

Aha, fount them! Thanks!
