### ISSUE TITLE
Where to find predicted regulatory transcription factors and corresponding targets in the output

### ISSUE THREAD

**Issue by yzz207** [liulab-dfci/MAESTRO#58]
The file XXX.PredictedTFTop10.txt has list of transcription factors. The tutorial mentions target genes should be in XXX.GIGGLE folder, but I couldn't find it. Could you point out which file I should look for? Thanks!

Yuping

**Comment by crazyhottommy** [comment]
it should be in `Result/Analysis/atac_pbmc_500_v1.PredictedTFTop10.txt`
