### ISSUE TITLE
Calculating gene variances: Error in simpleLoess(y, x, w, span, degree = degree, parametric = parametric,  :    invalid 'x'

### ISSUE THREAD

**Issue by bicnasong** [liulab-dfci/MAESTRO#59]
I ran MAESTRO workflow using fragment file as the input file and encountered the error.

<img width="1792" alt="Screen Shot 2020-09-21 at 12 57 09 PM" src="https://user-images.githubusercontent.com/62484339/93797641-7faae480-fc0a-11ea-9af4-fdc723b8f221.png">

Could you let me know why I have such an error? or how to solve it?

Thank you.

Bicna

**Comment by crazyhottommy** [comment]
@DongqingSun96 @taoliu have you encountered this before? @bicnasong do you have other error messages?

**Comment by bicnasong** [comment]
> @DongqingSun96 @taoliu have you encountered this before? @bicnasong do you have other error messages?

I think this error is related to this issue: https://github.com/liulab-dfci/MAESTRO/issues/61

**Comment by crazyhottommy** [comment]
this is fixed by https://github.com/liulab-dfci/MAESTRO/pull/65 if it is related to #61
