### ISSUE TITLE
Problem with ATACCalculateGenescore when choosing "GRCm38" 

### ISSUE THREAD

**Issue by yupingz** [liulab-dfci/MAESTRO#61]
genes = ATACCalculateGenescore(peaks, organism = "GRCm38")

this just give me a  zero matrix. And the column names are human gene names not mouse gene names.

**Comment by bicnasong** [comment]
I have the same problem.

**Comment by crazyhottommy** [comment]
@DongqingSun96 can you please double-check this? It could be a bug in the R version.
@yzz207 and @bicnasong thanks for reporting it, at the same time, can you try the python version as in here https://github.com/liulab-dfci/MAESTRO/blob/master/example/Gene_activity_modelling/Gene_activity_modelling.md

**Comment by bicnasong** [comment]
Thank you for the reply.

I think I need to load the peak matrix processed by 10x Cell Ranger pipelines to generate the gene regulatory score matrix by the following command.

> pbmc.peak <- Read10X_h5("10X_PBMC_10k/outs/filtered_peak_bc_matrix.h5")
> pbmc.gene <- ATACCalculateGenescore(pbmc.peaks, organism = "GRCh38")

The dataset I have is generated by in-house pipeline so I only have the raw sequencing fastq files. I am wondering only processed dataset from Cell Ranger pipelines can be used as the input file.

Thank you.

**Comment by bicnasong** [comment]
When I tried the python version as described in https://github.com/liulab-dfci/MAESTRO/blob/master/example/Gene_activity_modelling/Gene_activity_modelling.md, I got the following error message.

<img width="488" alt="Screen Shot 2020-09-29 at 4 04 07 PM" src="https://user-images.githubusercontent.com/62484339/94609939-83bfad80-026d-11eb-9973-af38209f1ed3.png">

**Comment by crazyhottommy** [comment]
How about  using the python command line tool `MAESTRO scatac-genescore`

**Comment by crazyhottommy** [comment]
> @DongqingSun96 can you please double-check this? It could be a bug in the R version.
> @yzz207 and @bicnasong thanks for reporting it, at the same time, can you try the python version as in here https://github.com/liulab-dfci/MAESTRO/blob/master/example/Gene_activity_modelling/Gene_activity_modelling.md

@DongqingSun96 it could be a bug in the R script for calculating gene activity scores.

**Comment by bicnasong** [comment]
> How about using the python command line tool `MAESTRO scatac-genescore`

When I used GRCh38, I was able to calculate gene activity scores without any problems. But if I use GRCm38, I keep getting error messages related to calculating gene activity scores (ATACCalculateGenescore and ATACAttachGeneScore).

By the way, we need a GIGGLE.table to visualize the driver TF for each cluster, but I couldn't find the file named project.name_giggle.txt. So, I just used the file named project.name.PredictedTFScore.txt instead, it seems to be working fine. Could you please tell me how I can generate the GIGGLE.table file?

**Comment by booew** [comment]
It seems that the annotation file for mouse ($CONDA_ENV/MAESTRO/lib/python3.7/site-packages/MAESTRO/annotations/**GRCm38_refgenes.txt**) provided in the MAESTRO pipeline was for **human genes**. Replace the file with the mouse refGenes.txt file downloaded from UCSC genome would fix this problem(remove the 'chr' characters in the chromosome column to ensure it's compatible).

**Comment by crazyhottommy** [comment]
Thanks @booew for reporting it! @DongqingSun96 can you please fix that? Thanks!

**Comment by suny1994** [comment]
> When I tried the python version as described in https://github.com/liulab-dfci/MAESTRO/blob/master/example/Gene_activity_modelling/Gene_activity_modelling.md, I got the following error message.
> 
> <img alt="Screen Shot 2020-09-29 at 4 04 07 PM" width="488" src="https://user-images.githubusercontent.com/62484339/94609939-83bfad80-026d-11eb-9973-af38209f1ed3.png">

Hi, have you resolved the problem that ModuleNotFoundError: No module named 'tables'?  I have the same problem.

**Comment by bc2zb** [comment]
Running into the same issue myself

```
pbmc.gene <- ATACCalculateGenescore(pbmc.peak, organism = "GRCh38", decaydistance = 10000, model = "Enhanced")
Error in py_run_file_impl(file, local, convert) : 
  ModuleNotFoundError: No module named 'tables'
```

**Comment by bc2zb** [comment]
Just commenting again as I think I've got it working, though the R command is completely bypassed in the process. Essentially, you call the command line from within R, load in the data, and then add it to the seurat ATAC object as your activity matrix prior to performing `ATACAnnotateTranscriptionFactor()`. Though, unless I'm mistaken, `ATACCalculateGenescore()` doesn't updated the seurat object to have the activity added anyways. 

```
library(MAESTRO)
library(Seurat)

pbmc.peak <- Read10X_h5("outs/filtered_peak_bc_matrix.h5")

system("MAESTRO scatac-genescore --format h5 --peakcount outs/filtered_peak_bc_matrix.h5 \
# --genedistance 10000 --species GRCh38 --model Enhanced -d 10X_PBMC_10k --outprefix 10X_PBMC_10k_10x")

pbmc.gene <- Read10X_h5("/data/capaldobj/CS025744_Beshiri_single_cell_atac/maestro_output/10X_PBMC_10k/10X_PBMC_10k_10x_gene_score.h5")

pbmc.ATAC.res <- ATACRunSeurat(inputMat = pbmc.peak,
                                 project = "10X_PBMC_10k",
                                 min.c = 50,
                                 min.p = 500,
                                 method = "LSI",
                                 dims.use = 1:30,
                                 cluster.res = 0.6,
                                 only.pos = TRUE,
                                 peaks.test.use = "presto",
                                 peaks.cutoff = 1e-05,
                                 peaks.pct = 0.1,
                                 peaks.logfc = 0.2)

pbmc.ATAC.res$ATAC <- ATACAnnotateChromatinAccessibility(ATAC = pbmc.ATAC.res$ATAC, 
                                                  peaks = pbmc.ATAC.res$peaks, 
                                                  project = "10X_PBMC_10k", 
                                                  giggle.path = "giggle.all",
                                                  organism = "GRCh38")

p <- DimPlot(result, label = TRUE, reduction = "umap", group.by = "biological_resource", repel=T, pt.size = 0.5, label.size = 2.5)
ggsave(file.path(paste0(result@project.name, "_CistromeTop_annotated.png")), p, width=7.5, height=4)

pbmc.gene <- pbmc.gene[,intersect(colnames(pbmc.ATAC.res$ATAC), colnames(pbmc.gene))]
pbmc.ATAC.res$ATAC <- SubsetData(pbmc.ATAC.res$ATAC, cells = intersect(colnames(pbmc.ATAC.res$ATAC), colnames(pbmc.gene)))

pbmc.ATAC.res$ATAC[["ACTIVITY"]] <- CreateAssayObject(counts = pbmc.gene) 
DefaultAssay(pbmc.ATAC.res$ATAC) <- "ACTIVITY" 
pbmc.ATAC.res$ATAC <- FindVariableFeatures(pbmc.ATAC.res$ATAC) 
pbmc.ATAC.res$ATAC <- NormalizeData(pbmc.ATAC.res$ATAC) 
pbmc.ATAC.res$ATAC <- ScaleData(pbmc.ATAC.res$ATAC)

pbmc.ATAC.tfs <- ATACAnnotateTranscriptionFactor(ATAC = pbmc.ATAC.res$ATAC, 
                                                   peaks = pbmc.ATAC.res$peaks, 
                                                   project = "10X_PBMC_10k", 
                                                   giggle.path = "giggle.all")
```

**Comment by crazyhottommy** [comment]
This was fixed by https://github.com/liulab-dfci/MAESTRO/pull/65 We will release 1.2.2 this week. Can you please try it again then? Thanks for reporting.

**Comment by crazyhottommy** [comment]
Please check the new v1.2.2 release, this should be fixed now!  closing this issue now. If you still have problems feel free to reopen it. Thanks!

**Comment by liying-1028** [comment]
> 

HI，I also encountered this problem, how did you solve it？
