### ISSUE TITLE
Suggestion to set default assay, fix hard coded lines and more in Incorporate.R 

### ISSUE THREAD

**Issue by taoliu** [liulab-dfci/MAESTRO#62]
To make this script more flexible for customized analysis, please add `DefaultAssay(ATAC) <- "ACTIVITY"` to the end of this code block. 

https://github.com/liulab-dfci/MAESTRO/blob/d58fc186a4329febde3b0d5b213c2d0edf8de44c/R/Incorporate.R#L47-L64

Also, please fix the hard code at:

https://github.com/liulab-dfci/MAESTRO/blob/d58fc186a4329febde3b0d5b213c2d0edf8de44c/R/Incorporate.R#L56

https://github.com/liulab-dfci/MAESTRO/blob/d58fc186a4329febde3b0d5b213c2d0edf8de44c/R/Incorporate.R#L84

https://github.com/liulab-dfci/MAESTRO/blob/d58fc186a4329febde3b0d5b213c2d0edf8de44c/R/Incorporate.R#L86

Another suggestion is to separate the plotting functions from this script since when users get the `CombinedObj`, they can plot whatever they want. To combine plotting with computation is unnecessary and will potentially cause some bugs.

**Comment by crazyhottommy** [comment]
was fixed by https://github.com/liulab-dfci/MAESTRO/pull/65
