### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by bc2zb** [liulab-dfci/MAESTRO#78]
It would be appreciated if the documentation explicitly mentioned that `rownames` of the input matrixes need to be gene symbols and not other annotations. Took me a while to figure out that `LISA` requires symbols, and that the mismatch in `rownames` of my ATAC and RNA data kept causing `Incorporate()` to segfault. However, I also admit I am using a slightly processed counts matrix for my RNA input, which used ensemble ids as the rownames.

**Comment by crazyhottommy** [comment]
@baigal628 can you please fix this? Thanks!

**Comment by crazyhottommy** [comment]
addressed by https://github.com/liulab-dfci/MAESTRO/pull/79
