### ISSUE TITLE
possible typo in the ATAC instruction page

### ISSUE THREAD

**Issue by QiangTU** [liulab-dfci/MAESTRO#83]
Hi, 

I ran MAESTRO by the Docker image successfully, then I tried to explore the data using R following the [instruction](https://github.com/liulab-dfci/MAESTRO/blob/master/example/ATAC_infrastructure_10x/ATAC_infrastructure_10x.md). In the step 4, there is:

```
p <- VisualizeTFenrichment(TFs = tfs,
                             cluster.1 = 0,
                             type = "ATAC",
                             SeuratObj = pbmc.ATAC.res$ATAC,
                             GIGGLE.table = "10X_PBMC_10k_giggle.txt",
                             visual.totalnumber = 100,
                             name = "10X_PBMC_10k_Monocyte_filtered")
```

I think the GIGGLE.table should be '10X_PBMC_10k.PredictedTFScore.txt', because in the directory, there is no such file named '10X_PBMC_10k_giggle.txt'.

Thanks!

**Comment by crazyhottommy** [comment]
Thanks Qiang! `10X_PBMC_10k.PredictedTFScore.txt` should be the right name. @baigal628 can you please fix this documentation?

**Comment by baigal628** [comment]
Thanks, Qiang. The typo has been fixed in the new release. We can close this issue now.

**Comment by crazyhottommy** [comment]
Thanks @baigal628 !
