### ISSUE TITLE
cluster resolution other than 0.6 with error in coembedding

### ISSUE THREAD

**Issue by strawberry789** [liulab-dfci/MAESTRO#84]
Hello,

I tried to cluster my scRNA and scATAC datasets using a resolution other than 0.6 (this number was used in the MAESTRO vignettes), but I got an error saying that  "ATAC_snn_res.0.6" or "RNA_snn_res.0.6" cannot be found in the Seurat object when I used the "Incorporate" function to coembed the two datasets.  Do I need to use a default resolution of 0.6 before coembedding?  But can I change the resolution after coembedding?

Thank you!

**Comment by crazyhottommy** [comment]
which version are you using? In the most recent version, we should have fixed this problem.  Can you please try to install it again?

**Comment by strawberry789** [comment]
I have re-installed the most updated v1.2.2, but this issue still remains.

**Comment by crazyhottommy** [comment]
we fixed this https://github.com/liulab-dfci/MAESTRO/commit/c06778f69cee2d1f4a2fffdd3847f3baba6cb28c
can you try installing it again?

**Comment by joseverdezoto** [comment]
@crazyhottommy  I just ran the integration step and came across the same issue. I installed the package last week though. Is it fixed now?

**Comment by baigal628** [comment]
> Hello,
> 
> I tried to cluster my scRNA and scATAC datasets using a resolution other than 0.6 (this number was used in the MAESTRO vignettes), but I got an error saying that "ATAC_snn_res.0.6" or "RNA_snn_res.0.6" cannot be found in the Seurat object when I used the "Incorporate" function to coembed the two datasets. Do I need to use a default resolution of 0.6 before coembedding? But can I change the resolution after coembedding?
> 
> Thank you!

Hi,

When running the Incorporate() function, make sure you are using the same resolutions as you used before when running scRNA-seq and scATAC-seq individually. Incorporate use the clustering results from input objects so should keep them consistent.

**Comment by baigal628** [comment]
@joseverdezoto

> @crazyhottommy I just ran the integration step and came across the same issue. I'm using the R package which I installed week though. Is it fixed now?

@joseverdezoto Hi, this issue should be fixed now. Could you please try again and let me know if there are still problems?
