### ISSUE TITLE
lisa unpack error

### ISSUE THREAD

**Issue by QiangTU** [liulab-dfci/MAESTRO#89]
Hi, I am running MAESTRO 1.2.2 following the tutorial. The scRNA-seq module complained:

`lisa unpack: error: argument tarball: ERROR: /home/qtu/work/maestro/lisa/hg38_2.1.tar.gz is not a valid file.
`

Actually I could directly execute `lisa unpack hg38_2.1.tar.gz` successful, not sure what caused the error.

BTW, does the option `--lisadir lisa/hg38_2.1.tar.gz` mean the pipeline will unpack the huge file  each time? 

Thanks!

**Comment by crazyhottommy** [comment]
Hi Qiang,
what's the output for 
`ls /home/qtu/work/maestro/lisa/hg38_2.1.tar.gz`?

and yes, it will do unpack every time, and we are aware of this. It takes ~10mins. We can think of skip this step if it is already done.

**Comment by QiangTU** [comment]
`
total 43G
-rw-r--r-- 1 qtu tulab 43G Feb 10  2020 lisa_v1.2_hg38.tar.gz
`

md5: `c3a78e555b032f459f2ab17d48d345d5`

**Comment by crazyhottommy** [comment]
that's strange. The file is there. 
and you can do `lisa unpack /home/qtu/work/maestro/lisa/hg38_2.1.tar.gz` interactively without problem?

**Comment by QiangTU** [comment]
Sorry, it is my bad! In the command line, I used `hg38_2.1.tar.gz` following the new instruction, but in the folder, I actually put the old file `lisa_v1.2_hg38.tar.gz` there! What a silly mistake! :-P 

BTW, `lisa_v1.2_hg38.tar.gz` is for LISA1  and `hg38_2.1.tar.gz` is for LISA2, right? The latter is much smaller, 20G only.

**Comment by crazyhottommy** [comment]
NP! yes, use`hg38_2.1.tar.gz` for lisa2.
