### ISSUE TITLE
two data files not accessible

### ISSUE THREAD

**Issue by QiangTU** [liulab-dfci/MAESTRO#92]
Hello,

I found two data files were not accessible:

http://cistrome.org/~chenfei/MAESTRO/Refdata_scATAC_MAESTRO_GRCh38_1.1.0.tar.gz
http://cistrome.org/~chenfei/MAESTRO/giggle.all.tar.gz

The error is 403 Forbidden.

**Comment by baigal628** [comment]
Hi Qiang,

Sorry about that.
I have generated new links here:

http://cistrome.org/~galib/giggle.all.tar.gz
http://cistrome.org/~galib/Refdata_scATAC_MAESTRO_GRCh38_1.1.0.tar.gz
http://cistrome.org/~galib/Refdata_scATAC_MAESTRO_GRCm38_1.1.0.tar.gz

We'll update this in the next release.

**Comment by crazyhottommy** [comment]
we updated it in the tutorial.
