### ISSUE TITLE
Error in integrating Seurat scRNA and Signac scATAC objects 

### ISSUE THREAD

**Issue by strawberry789** [liulab-dfci/MAESTRO#94]
First, I readRDS for my Seurat/harmony and Signac clustered scRNA and scATAC objects, respectively. 

Then, I tried to run the Incorporate function:
coembed <- Incorporate(RNA = rna, ATAC = atac, project = "Maestro_integrated", method = "MAESTRO")

But I get the following error:
Error: Cannot find 'ACTIVITY' in this Seurat object

I also tried:
coembed <- Incorporate(RNA = rna$RNA, ATAC = atac$ATAC, project = "Maestro_integrated", method = "MAESTRO")

But, 
Error: Cannot find 'ATAC' in this Seurat object

**Comment by crazyhottommy** [comment]
Do you have a gene activity count matrix named 'ACTIVITY' in your scATAC seurat object? if not, you need to create that count matrix following https://github.com/liulab-dfci/MAESTRO/blob/master/example/Gene_activity_modelling/Gene_activity_modelling.md and assign it to the Seurat object.

**Comment by crazyhottommy** [comment]
Please let us know if you still have this problem. If you run through MAESTRO snakemake pipeline you should have `ACTIVITY` in the Seurat object. if you are only using the MAESTRO R package, you may need to create the gene activity score and assign it to `ACTIVITY` in the Seurat slot.
